[project]
name = 'poc'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.insecure]
path = 'contracts/insecure.clar'
clarity_version = 2
epoch = 2.5

[contracts.malicious]
path = 'contracts/malicious.clar'
clarity_version = 2
epoch = 2.5

[contracts.timelock-wallet]
path = 'contracts/timelock-wallet.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
